using Machine.Specifications;
using GhostBridge;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GhostBridge.Sample.CSharp.MSpec.ChutzpahSpecs
{
    
    
    public sealed class with_nested_specs_sub1_passing_test_spec_0c3e9d6e626748c69a8e63a03bdb1e5d : GhostBridge.with_chutzpah_test_runner
    {
        
		Establish context = () => { testFile = @"C:\_src\ghost-bridge\src\GhostBridge.Sample.CSharp.MSpec\jasmine-specs\nested-specs\sub1\passing-test.spec.js"; chutzpahExe = @"..\..\..\..\lib\chutzpah\chutzpah.console.exe"; };
		Because of = () => Execute();
		It should_not_error = () => err.ShouldBeNull();
		It should_not_fail = () => ChutzpahTestRun.StdOut.ShouldNotContain("[FAIL]");
		It should_compile = () => ChutzpahTestRun.StdOut.ShouldNotContain("ERROR OCCURRED");
		It should_run_ok = () => ChutzpahTestRun.StdErr.ShouldBeEmpty();
    }
    
    public sealed class with_nested_specs_sub2_passing_test_spec_f2e08b5c84c54c0192e44f9fc83125b6 : GhostBridge.with_chutzpah_test_runner
    {
        
		Establish context = () => { testFile = @"C:\_src\ghost-bridge\src\GhostBridge.Sample.CSharp.MSpec\jasmine-specs\nested-specs\sub2\passing-test.spec.js"; chutzpahExe = @"..\..\..\..\lib\chutzpah\chutzpah.console.exe"; };
		Because of = () => Execute();
		It should_not_error = () => err.ShouldBeNull();
		It should_not_fail = () => ChutzpahTestRun.StdOut.ShouldNotContain("[FAIL]");
		It should_compile = () => ChutzpahTestRun.StdOut.ShouldNotContain("ERROR OCCURRED");
		It should_run_ok = () => ChutzpahTestRun.StdErr.ShouldBeEmpty();
    }
    
    public sealed class with_specs_failing_test_spec_6fb3367366544d3e9d690df54a4efefa : GhostBridge.with_chutzpah_test_runner
    {
        
		Establish context = () => { testFile = @"C:\_src\ghost-bridge\src\GhostBridge.Sample.CSharp.MSpec\jasmine-specs\specs\failing-test.spec.js"; chutzpahExe = @"..\..\..\..\lib\chutzpah\chutzpah.console.exe"; };
		Because of = () => Execute();
		It should_not_error = () => err.ShouldBeNull();
		It should_not_fail = () => ChutzpahTestRun.StdOut.ShouldNotContain("[FAIL]");
		It should_compile = () => ChutzpahTestRun.StdOut.ShouldNotContain("ERROR OCCURRED");
		It should_run_ok = () => ChutzpahTestRun.StdErr.ShouldBeEmpty();
    }
    
    public sealed class with_specs_passing_test_spec_4ae6270cd5724660b5980d0b9fbd68fb : GhostBridge.with_chutzpah_test_runner
    {
        
		Establish context = () => { testFile = @"C:\_src\ghost-bridge\src\GhostBridge.Sample.CSharp.MSpec\jasmine-specs\specs\passing-test.spec.js"; chutzpahExe = @"..\..\..\..\lib\chutzpah\chutzpah.console.exe"; };
		Because of = () => Execute();
		It should_not_error = () => err.ShouldBeNull();
		It should_not_fail = () => ChutzpahTestRun.StdOut.ShouldNotContain("[FAIL]");
		It should_compile = () => ChutzpahTestRun.StdOut.ShouldNotContain("ERROR OCCURRED");
		It should_run_ok = () => ChutzpahTestRun.StdErr.ShouldBeEmpty();
    }
}
