using Machine.Specifications;
using GhostBridge;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GhostBridge.Sample.VBNet.MSpec.ChutzpahSpecs
{
    
    
    public sealed class with_nested_specs_sub1_passing_test_spec_e35f7896fe6b4deb92a878f2c1b20c55 : GhostBridge.with_chutzpah_test_runner
    {
        
		Establish context = () => { testFile = @"C:\_src\ghost-bridge\src\GhostBridge.Sample.VBNet.MSpec\jasmine-specs\nested-specs\sub1\passing-test.spec.js"; chutzpahExe = @"..\..\..\..\lib\chutzpah\chutzpah.console.exe"; };
		Because of = () => Execute();
		It should_not_error = () => err.ShouldBeNull();
		It should_not_fail = () => ChutzpahTestRun.StdOut.ShouldNotContain("[FAIL]");
		It should_compile = () => ChutzpahTestRun.StdOut.ShouldNotContain("ERROR OCCURRED");
		It should_run_ok = () => ChutzpahTestRun.StdErr.ShouldBeEmpty();
    }
    
    public sealed class with_nested_specs_sub2_passing_test_spec_cfff704ca37d492197714b5e34ad19d5 : GhostBridge.with_chutzpah_test_runner
    {
        
		Establish context = () => { testFile = @"C:\_src\ghost-bridge\src\GhostBridge.Sample.VBNet.MSpec\jasmine-specs\nested-specs\sub2\passing-test.spec.js"; chutzpahExe = @"..\..\..\..\lib\chutzpah\chutzpah.console.exe"; };
		Because of = () => Execute();
		It should_not_error = () => err.ShouldBeNull();
		It should_not_fail = () => ChutzpahTestRun.StdOut.ShouldNotContain("[FAIL]");
		It should_compile = () => ChutzpahTestRun.StdOut.ShouldNotContain("ERROR OCCURRED");
		It should_run_ok = () => ChutzpahTestRun.StdErr.ShouldBeEmpty();
    }
    
    public sealed class with_specs_failing_test_spec_6c82c372fbe04728baf783503992d168 : GhostBridge.with_chutzpah_test_runner
    {
        
		Establish context = () => { testFile = @"C:\_src\ghost-bridge\src\GhostBridge.Sample.VBNet.MSpec\jasmine-specs\specs\failing-test.spec.js"; chutzpahExe = @"..\..\..\..\lib\chutzpah\chutzpah.console.exe"; };
		Because of = () => Execute();
		It should_not_error = () => err.ShouldBeNull();
		It should_not_fail = () => ChutzpahTestRun.StdOut.ShouldNotContain("[FAIL]");
		It should_compile = () => ChutzpahTestRun.StdOut.ShouldNotContain("ERROR OCCURRED");
		It should_run_ok = () => ChutzpahTestRun.StdErr.ShouldBeEmpty();
    }
    
    public sealed class with_specs_passing_test_spec_a381f4fcd8514ac79e9538c983487690 : GhostBridge.with_chutzpah_test_runner
    {
        
		Establish context = () => { testFile = @"C:\_src\ghost-bridge\src\GhostBridge.Sample.VBNet.MSpec\jasmine-specs\specs\passing-test.spec.js"; chutzpahExe = @"..\..\..\..\lib\chutzpah\chutzpah.console.exe"; };
		Because of = () => Execute();
		It should_not_error = () => err.ShouldBeNull();
		It should_not_fail = () => ChutzpahTestRun.StdOut.ShouldNotContain("[FAIL]");
		It should_compile = () => ChutzpahTestRun.StdOut.ShouldNotContain("ERROR OCCURRED");
		It should_run_ok = () => ChutzpahTestRun.StdErr.ShouldBeEmpty();
    }
}
